// Get Messages Constants
export const GET_MESSAGES_PENDING = "GET_MESSAGES_PENDING";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAILED = "GET_MESSAGES_FAILED";
// Add Message Constants
export const ADD_MESAGE_PENDING = "ADD_MESSAGE_PENDING";
export const ADD_MESAGE_SUCCESS = "ADD_MESSAGE_SUCCES";
export const ADD_MESAGE_FAILED = "ADD_MESSAGE_FAILED";
