// Get Friends Constants
export const GET_FRIEND_REQUESTS_PENDING = "GET_FRIEND_REQUESTS_PENDING";
export const GET_FRIEND_REQUESTS_SUCCESS = "GET_FRIEND_REQUESTS_SUCCESS";
export const GET_FRIEND_REQUESTS_FAILED = "GET_FRIEND_REQUESTS_FAILED";
